services:
  searxng:
    container_name: searxng-recollect
    image: searxng/searxng
    expose:
      - "${SEARXNG_PORT}"
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - SEARXNG_PORT=${SEARXNG_PORT}
      - SEARXNG_BIND_ADDRESS=${SEARXNG_BIND_ADDRESS}
      - SEARXNG_BASE_URL=${SEARXNG_URL}
      - SEARXNG_METHOD=${SEARXNG_METHOD}
  app:
    container_name: recollect-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:5000"
    depends_on:
      - searxng
    environment:
      - SEARXNG_URL=${SEARXNG_URL}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}